# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691ba9d941027ab83eecc70ca111e91ba5b42859c4e7e9b8e4ddc7778e85aa97d088e726e43f1e5254666ba4a53b68bb92d16c8b42b0e5c3d3f10b4ad31c4b6f

test:
  secret_key_base: 1004d2193a32f3a4a0b53f0f76a919013453ae23fa14b3d25b5553cc375d190383ded3835a121d7ed29b21965945d8a3498431a1b4f14f989eb7d1ed1075e955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
